#!/bin/bash

user=$(whoami)
home_dir="/home/$user"
files_count=$(find "$home_dir" -type f | wc -l)
hidden_count=$(find "$home_dir" -type f -name ".*" | wc -l)

echo "Домашний каталог пользователя"
echo "$user"
echo "содержит обычных файлов"
echo "$files_count"
echo "скрытых файлов"
echo "hidden_count"
